import { defineQuestionBank } from "./quizTypes";

export const convexQuestions = defineQuestionBank("凸函数小课堂", {
  middle: [
    {
      category: "优化目标",
      prompt: "一个优化问题最核心的任务通常是什么？",
      options: ["把所有变量都设为零", "在约束下最小化或最大化目标函数", "只画出函数图像", "随机选择一个可行点"],
      correct: 1,
      insight: "优化问题要在满足约束的候选方案中，寻找目标函数最小或最大的方案。",
    },
    {
      category: "凸集定义",
      prompt: "集合 C 是凸集，最准确的含义是什么？",
      options: ["C 只能包含两个点", "C 中任意两点的连线都留在 C 内", "C 的边界必须是圆", "C 中所有点到原点距离相同"],
      correct: 1,
      insight: "凸集的定义是：任取 x、y∈C 与 0≤θ≤1，点 θx+(1−θ)y 仍属于 C。",
    },
    {
      category: "凸集识别",
      prompt: "下面哪个一维集合一定是凸集？",
      options: ["闭区间 [−1, 2]", "两个孤立点 {−1, 2}", "并集 [−2,−1]∪[1,2]", "所有非零实数"],
      correct: 0,
      insight: "实数轴上的区间是凸集；分离的点或区间之间存在缺口，连线会离开集合。",
    },
    {
      category: "几何直觉",
      prompt: "在平面上，关于圆盘与圆周的说法哪项正确？",
      options: ["圆盘和圆周都不是凸集", "圆盘是凸集，圆周通常不是凸集", "圆周是凸集，圆盘不是凸集", "二者是否凸只由半径决定"],
      correct: 1,
      insight: "圆盘包含两点间的整条线段；圆周上两点的连线通常穿过圆内部，因此圆周本身不是凸集。",
    },
    {
      category: "仿射函数",
      prompt: "仿射函数 f(x)=3x−2 具有什么凸性？",
      options: ["只凸不凹", "只凹不凸", "既凸又凹", "既不凸也不凹"],
      correct: 2,
      insight: "任意仿射函数都同时是凸函数和凹函数。",
    },
    {
      category: "基础函数",
      prompt: "函数 f(x)=x² 在整个实数域上是什么函数？",
      options: ["凹函数", "仿射函数", "既不凸也不凹", "凸函数"],
      correct: 3,
      insight: "x² 的二阶导数恒为 2>0，因此它在实数域上是凸函数。",
    },
    {
      category: "基础函数",
      prompt: "函数 f(x)=−x² 在整个实数域上是什么函数？",
      options: ["严格凸函数", "仿射函数", "凹函数", "常数函数"],
      correct: 2,
      insight: "−x² 的二阶导数为 −2<0，因此它是凹函数。",
    },
    {
      category: "Jensen 不等式",
      prompt: "若 f 是凸函数、0≤θ≤1，Jensen 不等式的方向是哪一个？",
      options: ["f(θx+(1−θ)y)≤θf(x)+(1−θ)f(y)", "f(θx+(1−θ)y)≥θf(x)+(1−θ)f(y)", "f(x+y)=f(x)+f(y)", "f(θx)=θ²f(x)"],
      correct: 0,
      insight: "凸函数在两点连线中间的函数值，不高于端点函数值的线性插值。",
    },
    {
      category: "上图集",
      prompt: "函数 f 的上图集 epi f 指的是哪一组点？",
      options: ["满足 t≤f(x) 的 (x,t)", "满足 t=f(x) 的所有 x", "满足 t≥f(x) 的 (x,t)", "满足 f(x)=0 的 x"],
      correct: 2,
      insight: "上图集是函数图像上方的区域：epi f={(x,t) | t≥f(x)}。",
    },
    {
      category: "水平集",
      prompt: "若 f 是凸函数，它的次水平集 {x | f(x)≤α} 有什么性质？",
      options: ["一定只有一个点", "一定不是闭集", "一定是球面", "一定是凸集"],
      correct: 3,
      insight: "凸函数的每个次水平集都是凸集，这是识别和建模凸问题的重要性质。",
    },
    {
      category: "全局最优",
      prompt: "在凸可行域上最小化凸函数时，一个局部最优点同时是什么？",
      options: ["随机点", "不可行点", "全局最优点", "必然的最大值点"],
      correct: 2,
      insight: "凸优化最关键的好处之一，是局部最优不会与更好的全局最优分离。",
    },
    {
      category: "集合运算",
      prompt: "多个凸集的交集通常具有什么性质？",
      options: ["仍然是凸集", "一定为空集", "一定不是凸集", "只在二维时是凸集"],
      correct: 0,
      insight: "任意数量凸集的交集仍然凸，因此多个凸约束可以共同形成凸可行域。",
    },
    {
      category: "线性规划",
      prompt: "为什么线性规划属于凸优化？",
      options: ["因为它没有变量", "因为线性目标是凸的，线性等式与不等式形成凸可行域", "因为它只能手算", "因为所有答案都是整数"],
      correct: 1,
      insight: "线性函数是凸函数，半空间与仿射集合也是凸集，所以线性规划是凸优化。",
    },
    {
      category: "最小二乘",
      prompt: "普通线性最小二乘为什么是凸问题？",
      options: ["它没有目标函数", "参数必须是正数", "数据越多函数越凹", "残差平方和是凸二次函数"],
      correct: 3,
      insight: "目标 ‖Ax−b‖₂² 的 Hessian 为 2AᵀA，始终半正定。",
    },
    {
      category: "范数",
      prompt: "下面哪个函数是凸函数？",
      options: ["‖x‖₁", "−‖x‖₂", "−x⁴", "sin x 在整个实数域上"],
      correct: 0,
      insight: "所有范数都是凸函数；范数的负值通常是凹函数而非凸函数。",
    },
    {
      category: "保凸运算",
      prompt: "f₁ 和 f₂ 都是凸函数时，函数 max{f₁(x),f₂(x)} 是什么？",
      options: ["一定是凹函数", "一定是仿射函数", "无法定义", "一定是凸函数"],
      correct: 3,
      insight: "凸函数的逐点最大值仍然是凸函数。",
    },
    {
      category: "保凸运算",
      prompt: "f₁、f₂ 为凸函数，a、b≥0 时，af₁+bf₂ 具有什么性质？",
      options: ["一定凸", "一定凹", "只在 a=b 时凸", "只有 a、b 为负时凸"],
      correct: 0,
      insight: "凸函数的非负加权和仍保持凸性。",
    },
    {
      category: "梯度下降",
      prompt: "最小化可微函数时，梯度下降的典型更新是哪一个？",
      options: ["xₖ₊₁=xₖ+α∇f(xₖ)", "xₖ₊₁=xₖ−α∇f(xₖ)", "xₖ₊₁=∇f(xₖ)", "xₖ₊₁=αxₖ²"],
      correct: 1,
      insight: "负梯度方向是函数在当前点下降最快的一阶方向。",
    },
    {
      category: "步长选择",
      prompt: "梯度下降的步长 α 取得过大，常见风险是什么？",
      options: ["必然一步到最优", "目标函数自动变成线性", "可能振荡甚至发散", "梯度会永远等于零"],
      correct: 2,
      insight: "过大的步长可能反复越过低点；回溯线搜索等方法会帮助选择稳定步长。",
    },
    {
      category: "凸约束",
      prompt: "若 f 是凸函数，约束 f(x)≤0 所定义的可行集合通常是什么？",
      options: ["凹函数", "只能含整数", "一定无界", "凸集"],
      correct: 3,
      insight: "该可行域是凸函数的零次水平集，因此是凸集。",
    },
  ],
  university: [
    {
      category: "一阶条件",
      prompt: "可微函数 f 在凸域上为凸函数的一阶刻画是哪一个？",
      options: ["f(y)≥f(x)+∇f(x)ᵀ(y−x)", "f(y)≤f(x)+∇f(x)ᵀ(y−x)", "∇f(x)=0 对所有 x", "f(x+y)=f(x)f(y)"],
      correct: 0,
      insight: "凸函数的切平面是全局下界，这是一阶凸性条件。",
    },
    {
      category: "二阶条件",
      prompt: "二次可微函数在凸开集上为凸函数，常用的 Hessian 条件是什么？",
      options: ["∇²f(x) 负定", "∇²f(x) 半正定", "∇²f(x) 的迹为零", "∇²f(x) 必须是单位阵"],
      correct: 1,
      insight: "Hessian 半正定表示函数沿每个方向的二阶曲率都非负。",
    },
    {
      category: "强凸性",
      prompt: "一个强凸函数如果存在最小点，该最小点有什么特点？",
      options: ["一定不唯一", "一定唯一", "一定在边界外", "一定使函数值为零"],
      correct: 1,
      insight: "强凸性提供正的曲率下界，因此排除了两个不同全局最小点。",
    },
    {
      category: "仿射复合",
      prompt: "f 是凸函数时，g(x)=f(Ax+b) 具有什么性质？",
      options: ["仍为凸函数", "必为凹函数", "只有 A 可逆时才凸", "只有 b=0 时才凸"],
      correct: 0,
      insight: "凸函数与仿射映射复合会保持凸性，不要求 A 可逆。",
    },
    {
      category: "标量复合",
      prompt: "f 为凸函数，g 为凸且单调不减函数时，g∘f 通常是什么？",
      options: ["凹函数", "仿射函数", "凸函数", "常数函数"],
      correct: 2,
      insight: "外层凸且单调不减、内层凸，是常用的保凸复合规则。",
    },
    {
      category: "透视函数",
      prompt: "若 f 是凸函数，它的透视函数通常写成什么形式？",
      options: ["tf(tx)", "t f(x/t)，其中 t>0", "f(x)+t²", "f(tx)/t²，任意 t"],
      correct: 1,
      insight: "透视变换 g(x,t)=t f(x/t) 在 t>0 上保持凸性。",
    },
    {
      category: "逐点上确界",
      prompt: "一族凸函数 {fᵢ} 的逐点上确界 supᵢ fᵢ(x) 通常是什么？",
      options: ["凸函数", "凹函数", "只在有限族时凸", "一定不可微且不凸"],
      correct: 0,
      insight: "任意族凸函数的逐点上确界仍然凸；不可微不等于不凸。",
    },
    {
      category: "典型函数",
      prompt: "函数 log(∑ᵢ exp(xᵢ)) 具有什么凸性？",
      options: ["凹", "仿射", "凸", "只在 xᵢ>0 时凸"],
      correct: 2,
      insight: "log-sum-exp 是平滑凸函数，也常被视作最大值函数的平滑近似。",
    },
    {
      category: "共轭函数",
      prompt: "f 的 Fenchel 共轭 f*(y) 定义为什么？",
      options: ["infₓ(f(x)+yᵀx)", "supₓ(yᵀx−f(x))", "f(y)²", "∇f(y)"],
      correct: 1,
      insight: "Fenchel 共轭是仿射函数 yᵀx−f(x) 关于 x 的上确界。",
    },
    {
      category: "共轭函数",
      prompt: "无论原函数 f 是否凸，它的共轭函数 f* 总具有什么性质？",
      options: ["总是凸函数", "总是凹函数", "总是线性函数", "总是有限值函数"],
      correct: 0,
      insight: "f* 是一族关于 y 的仿射函数的逐点上确界，因此总是凸的。",
    },
    {
      category: "弱对偶",
      prompt: "对一个最小化问题，弱对偶说明什么？",
      options: ["对偶值总大于原问题值", "原问题与对偶问题必有相同解", "任意对偶可行值不超过任意原问题可行值", "对偶问题一定不可行"],
      correct: 2,
      insight: "对偶函数给出原问题最优值的下界，因此 d*≤p*。",
    },
    {
      category: "Slater 条件",
      prompt: "对满足常规条件的凸问题，Slater 条件最常用来保证什么？",
      options: ["目标函数变成线性", "强对偶成立", "所有约束都失效", "梯度恒为零"],
      correct: 1,
      insight: "存在严格可行点的 Slater 条件通常可保证零对偶间隙，并支持 KKT 必要性。",
    },
    {
      category: "拉格朗日乘子",
      prompt: "采用约束 fᵢ(x)≤0 的写法时，对应的不等式乘子 λᵢ 应满足什么？",
      options: ["λᵢ≥0", "λᵢ≤0", "λᵢ=1", "λᵢ 必须是整数"],
      correct: 0,
      insight: "对最小化问题的标准不等式形式 fᵢ(x)≤0，拉格朗日乘子要求非负。",
    },
    {
      category: "KKT 条件",
      prompt: "在凸问题中，一个点满足原始可行、对偶可行、驻点性和互补松弛时，可推出什么？",
      options: ["它一定是最大值", "它一定不可行", "它是全局最优解", "只能说明梯度非零"],
      correct: 2,
      insight: "对凸问题，KKT 条件具有充分性；满足这些条件即可认证全局最优。",
    },
    {
      category: "无约束最优",
      prompt: "可微凸函数 f 在点 x* 满足 ∇f(x*)=0，可得出什么？",
      options: ["x* 是全局最大点", "f 一定强凸", "x* 一定不是唯一解", "x* 是全局最小点"],
      correct: 3,
      insight: "凸函数的切平面是全局下界，零梯度意味着没有方向能得到更小的一阶下界。",
    },
    {
      category: "投影梯度",
      prompt: "投影梯度法每步在梯度更新后增加了哪项操作？",
      options: ["删除目标函数", "把梯度乘以零", "投影回可行凸集", "随机改变约束"],
      correct: 2,
      insight: "典型更新为 xₖ₊₁=Π_C(xₖ−α∇f(xₖ))，投影保证新点回到可行集。",
    },
    {
      category: "近端算子",
      prompt: "proxₜf(x) 的标准定义是哪一个？",
      options: ["argmax_z f(z)", "x−t f(x)", "∇²f(x)x", "argmin_z {f(z)+‖z−x‖₂²/(2t)}"],
      correct: 3,
      insight: "近端算子在降低 f 与靠近当前点之间折中，适合处理非光滑凸项。",
    },
    {
      category: "Lasso",
      prompt: "Lasso 目标 ‖Ax−b‖₂²+λ‖x‖₁（λ≥0）的特点是什么？",
      options: ["一定非凸", "处处二次可微", "只在 A 为方阵时凸", "凸但因 L1 项可能不可微"],
      correct: 3,
      insight: "平方损失和 L1 范数都是凸函数，但 L1 范数在分量为零处不可微。",
    },
    {
      category: "半定规划",
      prompt: "半定规划中 X⪰0 表示什么？",
      options: ["X 的所有元素都为正", "X 必须是单位阵", "X 的行列式必须为负", "X 是对称半正定矩阵"],
      correct: 3,
      insight: "X⪰0 表示 X 对称且所有特征值非负，这是一个凸锥约束。",
    },
    {
      category: "二阶锥规划",
      prompt: "下面哪个约束是典型的二阶锥约束？",
      options: ["sin(x)≤0", "x₁x₂=1", "x 只能取质数", "‖Ax+b‖₂≤cᵀx+d"],
      correct: 3,
      insight: "仿射表达式的二范数不超过仿射标量，是标准二阶锥约束形式。",
    },
  ],
  phd: [
    {
      category: "次梯度",
      prompt: "向量 g 是凸函数 f 在 x 处的次梯度，意味着对所有 y 有什么？",
      options: ["f(y)≥f(x)+gᵀ(y−x)", "f(y)≤f(x)+gᵀ(y−x)", "g=0 必须成立", "f(y)=gᵀy"],
      correct: 0,
      insight: "次梯度定义了支撑超平面；可微时，唯一的次梯度就是梯度。",
    },
    {
      category: "非光滑最优性",
      prompt: "对适当的凸函数 f，无约束点 x* 为全局最小点的条件是什么？",
      options: ["∂f(x*) 为空", "0∈∂f(x*)", "f(x*) 必须等于 0", "所有次梯度范数都等于 1"],
      correct: 1,
      insight: "零向量属于次微分，是可微情形 ∇f(x*)=0 的非光滑推广。",
    },
    {
      category: "约束最优性",
      prompt: "最小化 f(x) 且 x∈C 时，凸分析中的最优性条件可写成什么？",
      options: ["∂f(x*)=C", "x*=∇f(x*)", "0∈∂f(x*)+N_C(x*)", "N_C(x*) 必须为空"],
      correct: 2,
      insight: "目标函数次微分与可行集法锥之和包含零，统一表达了约束下的一阶最优性。",
    },
    {
      category: "Fenchel–Young",
      prompt: "Fenchel–Young 不等式是哪一个？",
      options: ["f(x)+f*(y)≤xᵀy", "f(x)f*(y)=xᵀy", "f*(y)=−f(y)", "f(x)+f*(y)≥xᵀy"],
      correct: 3,
      insight: "该不等式直接来自共轭定义；当 y∈∂f(x) 时取等号。",
    },
    {
      category: "范数共轭",
      prompt: "范数 f(x)=‖x‖ 的 Fenchel 共轭是什么？",
      options: ["对偶范数单位球的示性函数", "同一个范数", "范数的负值", "处处为零"],
      correct: 0,
      insight: "当 ‖y‖*≤1 时共轭值为 0，否则为 +∞；这里 ‖·‖* 是对偶范数。",
    },
    {
      category: "锥对偶",
      prompt: "实对称半正定锥 S₊ⁿ 的对偶锥是什么？",
      options: ["负半定锥", "它自身 S₊ⁿ", "整个矩阵空间", "只有零矩阵"],
      correct: 1,
      insight: "在迹内积下，半正定锥是自对偶锥。",
    },
    {
      category: "Schur 补",
      prompt: "若 A≻0，分块矩阵 [[A,B],[Bᵀ,C]]⪰0 等价于什么？",
      options: ["C+BᵀA⁻¹B≺0", "A=B=C", "C−BᵀA⁻¹B⪰0", "det(A)=0"],
      correct: 2,
      insight: "A 正定时，分块半正定条件可用 Schur 补 C−BᵀA⁻¹B⪰0 表示。",
    },
    {
      category: "互补松弛",
      prompt: "标准不等式 fᵢ(x)≤0 的 KKT 互补松弛条件是什么？",
      options: ["λᵢ+fᵢ(x*)=0", "λᵢ=fᵢ(x*)", "λᵢ>0 且 fᵢ(x*)<0", "λᵢfᵢ(x*)=0"],
      correct: 3,
      insight: "乘子与约束松弛量不能同时非零；非活跃约束对应的最优乘子为零。",
    },
    {
      category: "等式乘子",
      prompt: "拉格朗日对偶中，等式约束 h(x)=0 的乘子 ν 通常有什么符号限制？",
      options: ["没有符号限制", "必须非负", "必须非正", "必须等于 1"],
      correct: 0,
      insight: "等式约束乘子可以取任意实数，不同于标准不等式约束的非负乘子。",
    },
    {
      category: "对偶证书",
      prompt: "找到原始可行点 x 和对偶可行点 (λ,ν) 后，p(x)−d(λ,ν) 有什么意义？",
      options: ["一定为负", "给出当前解次优程度的上界证书", "等于梯度范数", "与最优性无关"],
      correct: 1,
      insight: "弱对偶保证该间隙非负，它界定了当前原始目标距离最优值最多还有多远。",
    },
    {
      category: "障碍法",
      prompt: "含 m 个不等式约束的对数障碍法中，中心路径点常见的对偶间隙是多少？",
      options: ["t/m", "m·t", "m/t", "1/(m·t²)"],
      correct: 2,
      insight: "采用 t f₀(x)+φ(x) 的参数化时，中心路径对应的对偶间隙为 m/t。",
    },
    {
      category: "中心路径",
      prompt: "在标准障碍法中逐步增大参数 t，中心路径点通常会怎样？",
      options: ["远离可行域", "使所有乘子为负", "把目标函数变成常数", "逼近原约束问题的最优解"],
      correct: 3,
      insight: "t 墈大时障碍问题更重视原目标，且 m/t 下降，中心路径逐步逼近最优点。",
    },
    {
      category: "Newton 减量",
      prompt: "在无约束凸优化的 Newton 法中，Newton 减量主要用来做什么？",
      options: ["衡量局部接近最优的程度并辅助停止判断", "计算数据样本数", "替代可行域", "保证 Hessian 为零"],
      correct: 0,
      insight: "Newton 减量由梯度与 Hessian 决定，在局部区域可估计次优程度。",
    },
    {
      category: "KKT 线性系统",
      prompt: "等式约束 Newton 步通常通过哪类系统求解？",
      options: ["只有一个标量方程", "由 Hessian 与约束矩阵组成的鞍点 KKT 线性系统", "纯随机采样", "傅里叶级数"],
      correct: 1,
      insight: "Newton 方向与等式乘子增量共同出现在分块 KKT 系统中。",
    },
    {
      category: "梯度复杂度",
      prompt: "对光滑凸函数，基本梯度法在常见假设下的函数值收敛率通常是哪一个？",
      options: ["O(k)", "O(2ᵏ)", "O(1/k)", "一步精确收敛"],
      correct: 2,
      insight: "光滑凸情形下，合适固定步长的基本梯度法通常达到 O(1/k) 的函数值误差。",
    },
    {
      category: "加速方法",
      prompt: "Nesterov 加速梯度法对光滑凸问题的典型函数值收敛率是什么？",
      options: ["O(k²)", "O(log k) 的误差", "与 k 无关", "O(1/k²)"],
      correct: 3,
      insight: "加速方法通过动量式外推，将一般光滑凸问题的典型速率提升到 O(1/k²)。",
    },
    {
      category: "线性收敛",
      prompt: "当目标同时 L-光滑且 μ-强凸时，合适步长的梯度法通常呈现什么收敛？",
      options: ["几何（线性）收敛", "只能 O(1/√k)", "一定发散", "有限一步收敛"],
      correct: 0,
      insight: "强凸性与光滑性共同带来按固定比例缩小误差的线性收敛，其速度受条件数 L/μ 影响。",
    },
    {
      category: "近端最优性",
      prompt: "对闭凸函数 f，x* 为其最小点与哪个近端不动点条件等价？",
      options: ["x*=−proxₜf(x*)", "x*=proxₜf(x*)，t>0", "proxₜf(x*)=0 对所有问题", "x*=t∇f(x*)"],
      correct: 1,
      insight: "最小点满足 0∈∂f(x*)，代入近端最优性条件即可得到不动点关系。",
    },
    {
      category: "ADMM",
      prompt: "ADMM 最适合利用哪类结构？",
      options: ["完全没有变量的问题", "只能取整数的任意非凸问题", "可分目标 f(x)+g(z) 与线性耦合约束 Ax+Bz=c", "目标函数未知的问题"],
      correct: 2,
      insight: "ADMM 交替处理可分目标的两个变量块，并通过乘子更新协调线性约束。",
    },
    {
      category: "拟凸优化",
      prompt: "拟凸目标的最小化常可怎样转化求解？",
      options: ["只检查 Hessian 负定", "把所有约束删除", "枚举所有实数", "对目标水平做二分搜索，并反复检查凸次水平集可行性"],
      correct: 3,
      insight: "拟凸函数的次水平集为凸集，因此可对候选目标值做二分与凸可行性检验。",
    },
  ],
});
